version: '3.8'

services:
  marketing-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-compose-app
    ports:
      - "9005:80"
    restart: always
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - ecommerce-net

  postgres-db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: krzysztof
      POSTGRES_PASSWORD: MojeSuperHaslo123
      POSTGRES_DB: ecom_data
    networks:
      - ecommerce-net
    # ZAUWAŻ: Nie ma tutaj sekcji "ports"! Baza jest niewidoczna z zewnątrz.

networks:
  ecommerce-net:
    driver: bridge